### ISSUE TITLE
[feature] Configuration location change

### ISSUE THREAD

**Issue by cadriel** [discourse/discourse_theme#5]
Would it be possible to;

- Instead of storing the configuration in `~/.discourse_theme`, instead have it optionally read from the theme folder. By default upon creation - the `.gitignore` could exclude this.

This'd mean you could be working on multiple themes against different instances without having to manage configuration constantly.

- Further to the above; the current expectation is to run `discourse_theme` from outside of the theme folder you're running. How about running within the intended theme folder when watching?

If you do this - then you can read the above mentioned config from the same folder if detected - with the added benefit of not having to pass in the theme path as an option.

All of this also means self contained configuration - i.e., not having some config written to your home folder.

**Comment by SamSaffron** [comment]
but ~/.discourse_theme is already keyed per directory 

https://github.com/discourse/discourse_theme/blob/master/test/test_config.rb#L33-L36

I left it out of the directory to restrict risk of people getting a .gitignore wrong.
